name: Build Installers

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          npm install
          cd client && npm install && cd ..

      - name: Build client
        working-directory: ${{ github.workspace }}
        run: cd client && npm run build && cd ..

      - name: Prepare build directory
        working-directory: ${{ github.workspace }}
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            if (Test-Path build) { Remove-Item -Recurse -Force build }
            New-Item -ItemType Directory -Force -Path build
            Copy-Item -Path dist,electron,package.json,public -Destination build -Recurse
          else
            rm -rf build
            mkdir -p build
            cp -r dist electron package.json public build/
          fi

      - name: Build installers
        working-directory: ${{ github.workspace }}/build
        run: |
          # Show build directory contents
          if [ "${{ runner.os }}" == "Windows" ]; then
            echo "Build directory contents:"
            dir
          else
            echo "Build directory contents:"
            ls -la
          fi
          # Run the build command
          npm run electron:build
        env:
          # Skip code signing
          CSC_IDENTITY_AUTO_DISCOVERY: "false"
          CSC_LINK: ""
          CSC_KEY_PASSWORD: ""
          # Set the correct path for electron-builder
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: "true"

      - name: Get platform info
        id: platform
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            echo "platform=win" >> $GITHUB_OUTPUT
            echo "arch=x64" >> $GITHUB_OUTPUT
          elif [ "${{ runner.os }}" == "macOS" ]; then
            echo "platform=mac" >> $GITHUB_OUTPUT
            if [ "${{ runner.arch }}" == "arm64" ]; then
              echo "arch=arm64" >> $GITHUB_OUTPUT
            else
              echo "arch=x64" >> $GITHUB_OUTPUT
            fi
          else
            echo "platform=linux" >> $GITHUB_OUTPUT
            echo "arch=x64" >> $GITHUB_OUTPUT
          fi

      - name: Upload installers
        uses: actions/upload-artifact@v4
        with:
          name: bitbon-${{ steps.platform.outputs.platform }}-${{ steps.platform.outputs.arch }}
          path: ${{ github.workspace }}/release/
          if-no-files-found: error 