name: Build Installers

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: macos-latest
            platform: mac
            arch: arm64
          - os: macos-latest
            platform: mac
            arch: x64
          - os: windows-latest
            platform: win
            arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: x64

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          npm install --ignore-scripts
          cd client && npm install --ignore-scripts && cd ..

      - name: Build client
        working-directory: ${{ github.workspace }}
        run: cd client && npm run build && cd ..

      - name: Create build directory
        working-directory: ${{ github.workspace }}
        run: |
          rm -rf build
          mkdir -p build
          cp -r dist electron package.json package-lock.json public build/
          if [ "${{ runner.os }}" == "Windows" ]; then
            mkdir -p build/build
            echo "Created build/build directory for Windows"
          fi

      - name: Install build dependencies (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        working-directory: ${{ github.workspace }}/build
        run: |
          npm install --ignore-scripts
          npm install electron@36.2.0 electron-builder@26.0.12 --save-dev --save-exact --ignore-scripts
          npm rebuild --build-from-source
          Write-Host "Installed dependencies in build directory"

      - name: Install build dependencies (Unix)
        if: runner.os != 'Windows'
        working-directory: ${{ github.workspace }}/build
        run: |
          npm install --ignore-scripts
          npm install electron@36.2.0 electron-builder@26.0.12 --save-dev --save-exact --ignore-scripts
          npm rebuild --build-from-source
          echo "Installed dependencies in build directory"

      - name: Verify build setup
        working-directory: ${{ github.workspace }}/build
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            dir
            dir node_modules
            type package.json | findstr electron
          else
            ls -la
            ls -la node_modules
            grep electron package.json
          fi

      - name: Build installers
        working-directory: ${{ github.workspace }}/build
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            npx electron-builder --win --x64 --publish=never
          elif [ "${{ runner.os }}" == "macOS" ]; then
            if [ "${{ matrix.arch }}" == "arm64" ]; then
              npx electron-builder --mac --arm64 --publish=never
            else
              npx electron-builder --mac --x64 --publish=never
            fi
          else
            npx electron-builder --linux --x64 --publish=never
          fi
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: "false"
          CSC_LINK: ""
          CSC_KEY_PASSWORD: ""
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: "true"

      - name: Verify artifacts
        working-directory: ${{ github.workspace }}
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            dir release
          else
            ls -la release
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          files: |
            ${{ github.workspace }}/release/*.exe
            ${{ github.workspace }}/release/*.dmg
            ${{ github.workspace }}/release/*.zip
            ${{ github.workspace }}/release/*.AppImage
            ${{ github.workspace }}/release/*.deb
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bitbon-${{ matrix.platform }}-${{ matrix.arch }}
          path: ${{ github.workspace }}/release/
          if-no-files-found: error 