name: Build Installers

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          npm install
          cd client && npm install && cd ..

      - name: Build client
        working-directory: ${{ github.workspace }}
        run: cd client && npm run build && cd ..

      - name: Prepare build directory (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        working-directory: ${{ github.workspace }}
        run: |
          if (Test-Path build) { Remove-Item -Recurse -Force build }
          New-Item -ItemType Directory -Force -Path build
          Copy-Item -Path dist,electron,package.json,package-lock.json,public -Destination build -Recurse
          Set-Location build
          npm install --omit=dev
          npm install electron@36.2.0 --save-exact
          Set-Location ..

      - name: Prepare build directory (Unix)
        if: runner.os != 'Windows'
        working-directory: ${{ github.workspace }}
        run: |
          rm -rf build
          mkdir -p build
          cp -r dist electron package.json package-lock.json public build/
          cd build
          npm install --omit=dev
          npm install electron@36.2.0 --save-exact
          cd ..

      - name: Build installers (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        working-directory: ${{ github.workspace }}/build
        run: |
          Write-Host "Build directory contents:"
          Get-ChildItem
          Write-Host "Node modules:"
          Get-ChildItem node_modules
          Write-Host "Package.json:"
          Get-Content package.json | Select-String "electron"
          electron-builder --publish=never
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: "false"
          CSC_LINK: ""
          CSC_KEY_PASSWORD: ""
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: "true"

      - name: Build installers (Unix)
        if: runner.os != 'Windows'
        working-directory: ${{ github.workspace }}/build
        run: |
          echo "Build directory contents:"
          ls -la
          echo "Node modules:"
          ls -la node_modules
          echo "Package.json electron version:"
          grep electron package.json
          electron-builder --publish=never
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: "false"
          CSC_LINK: ""
          CSC_KEY_PASSWORD: ""
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: "true"

      - name: Get platform info
        id: platform
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            echo "platform=win" >> $GITHUB_OUTPUT
            echo "arch=x64" >> $GITHUB_OUTPUT
          elif [ "${{ runner.os }}" == "macOS" ]; then
            echo "platform=mac" >> $GITHUB_OUTPUT
            if [ "${{ runner.arch }}" == "arm64" ]; then
              echo "arch=arm64" >> $GITHUB_OUTPUT
            else
              echo "arch=x64" >> $GITHUB_OUTPUT
            fi
          else
            echo "platform=linux" >> $GITHUB_OUTPUT
            echo "arch=x64" >> $GITHUB_OUTPUT
          fi

      - name: Upload installers
        uses: actions/upload-artifact@v4
        with:
          name: bitbon-${{ steps.platform.outputs.platform }}-${{ steps.platform.outputs.arch }}
          path: ${{ github.workspace }}/release/
          if-no-files-found: error 