name: Build and Release

on:
  push:
    tags:
      - 'v*'

# Add permissions block at the workflow level
permissions:
  contents: write  # Required for creating releases
  packages: write  # Required for uploading release assets

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}  # Use PAT for checkout

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install
          cd client && npm install && cd ..

      - name: Build client
        run: cd client && npm run build && cd ..

      - name: Build/Release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.PAT_TOKEN }}  # Use PAT for release
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          # Skip code signing for now
          mac_certs: ""
          mac_certs_password: ""
          windows_certs: ""
          windows_certs_password: ""
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use PAT for GitHub API
          # Skip code signing on macOS
          CSC_IDENTITY_AUTO_DISCOVERY: "false"
          # Skip code signing on Windows
          CSC_LINK: ""
          CSC_KEY_PASSWORD: "" 