name: Build Installers

on:
  push:
    tags:
      - 'v*'

# Update permissions to include releases
permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    # Set a timeout for each job
    timeout-minutes: 30

    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm cache clean --force
          npm install
          cd client && npm install && cd ..

      - name: Generate icons
        run: npm run generate-icons

      - name: Build client
        run: cd client && npm run build && cd ..

      - name: Debug directory structure
        run: |
          echo "Current directory structure:"
          ls -la
          echo "\nClient directory:"
          ls -la client
          echo "\nClient dist directory:"
          ls -la client/dist || echo "Client dist directory not found"
          echo "\nBuild directory:"
          ls -la build || echo "Build directory not found"
          echo "\nPublic directory:"
          ls -la public || echo "Public directory not found"

      - name: Build installer
        env:
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: "true"
          ELECTRON_BUILDER_SKIP_CODE_SIGNING: "true"
          DEBUG: "electron-builder"
        run: |
          rm -rf node_modules/.cache
          rm -rf release
          rm -rf build
          npm run electron:build
          echo "\nAfter build - Release directory:"
          ls -la release || echo "Release directory not found"
          echo "\nBuild directory contents:"
          ls -la build || echo "Build directory not found"

      - name: Debug build output
        run: |
          echo "Final directory structure:"
          ls -la
          echo "\nRelease directory contents:"
          ls -la release || echo "Release directory not found"
          echo "\nBuild directory contents:"
          ls -la build || echo "Build directory not found"
          if [ -d "release" ]; then
            echo "\nRelease directory details:"
            find release -type f -ls
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bitbon-${{ matrix.platform }}-${{ matrix.arch }}
          path: release/
          if-no-files-found: warn

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
          draft: false
          prerelease: false
          generate_release_notes: true
          fail_on_unmatched_files: false 